### ISSUE TITLE
use of unstable library feature 'rustc_private'

### ISSUE THREAD

**Issue by Aeradriel** [djudd/human-name#2]
For some days, human-name won't compile on nightly due to the following error :

> use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812).
help: add #![feature(rustc_private)] to the crate attributes to enable

This error refers to the libc crate.

**Comment by djudd-stripe** [comment]
Hi - can you try again? I believe I just fixed this a couple of days ago, and libc is now in Cargo.toml - https://github.com/djudd/human-name/blob/master/Cargo.toml#L18

**Comment by Aeradriel** [comment]
Hi,

Thanks for your fast answer. I see in the Cargo.toml that it is indeed in 0.7.1 but the last version published to crates.io is 0.7.0 (https://crates.io/crates/human_name). Did you release this version yet ?

**Comment by djudd-stripe** [comment]
Oops, had not, but now have. Thanks!

**Comment by Aeradriel** [comment]
Works great now thanks !
