### ISSUE TITLE
Can't use as lib nor install binary

### ISSUE THREAD

**Issue by terry90** [djudd/human-name#3]
On Manjaro (Arch), I can't manage to install human name

`/tmp/cargo-installT7y29w/release/deps/libphf_macros-e2da2247ec3ad74d.so: undefined symbol: __rustc_plugin_registrar_b30a24958c69eff7b4c31bba00cda158__`

In a project or with `cargo install`, I have similar error output.

Edit:
Same on a musl docker image

```
warning: dropping unsupported crate type `dylib` for target `x86_64-unknown-linux-musl`

error: /app/target/release/deps/libphf_macros-483b69f9520725a9.so: undefined symbol: __rustc_plugin_registrar_ca6c90974db93022f7f4ec3d3a5f2bd__
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/human_name-0.8.0/src/lib.rs:9:11
  |
9 | #![plugin(phf_macros)]
  |           ^^^^^^^^^^

```

**Comment by terry90** [comment]
@djudd I think the CI build is broken because of this too

**Comment by djudd** [comment]
I think it might be fixed. I'm not totally sure because I can only reproduce locally using `cargo publish --dry-run` for reasons I don't yet understand, and the build appears to be broken now because of some unrelated Travis issue. Can you let me know if it works for you?

**Comment by terry90** [comment]
Oh nice, thanks for your quick reaction.
It works as expected !
