### ISSUE TITLE
Name leads to unhandable panic

### ISSUE THREAD

**Issue by juma121** [djudd/human-name#5]
For example: "Peter Martin-Le Bore".consistend_with(&"Peter Martin-Le Bore)  results in a panic due to the following error:  "thread 'main' panicked at 'attempt to subtract with overflow', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/human_name-1.0.1/src/comparison.rs:204:21".

**Comment by djudd** [comment]
Thanks for the report! I'll try to take a look this weekend.

**Comment by djudd** [comment]
Fix was a bit of a quick hack since I didn't end up having time to page this code back into my memory but it seems to work!

**Comment by djudd** [comment]
`consistent_with` is apparently pretty under-testing relative to parsing. Shame on 5-years-ago me.

**Comment by juma121** [comment]
Thanks for the fix! Apart from a few very uncommon names the crate works super well for my usecase! Great work :)
