### ISSUE TITLE
Extracting honorific prefix and postfix

### ISSUE THREAD

**Issue by nokome** [djudd/human-name#6]
First, thank you for `human-name`, I'm finding it really useful.

I'd like to be able to extract "honorific" prefixes and postfixes. I have seen `find_prefix_len` and `find_postfix_index` in https://github.com/djudd/human-name/blob/3e43df16c60f1101fb8feeed1ba1b65a390beb59/src/title.rs but this module is private, and in anycase I am unsure how best to use them without re-parsing the name.

Would it make sense to have `Name::honorific_prefix()` and `Name::honorific_suffix()` and rename `suffix` to `Name::generational_suffix()`?

**Comment by djudd** [comment]
I'm glad you've found it useful!

I'd be happy to take a PR to preserve title/honorific information; there's no particular reason that's not supported except that my original use case didn't need it.

Thoughts on your proposed API: 
* We probably want to support multiple honorifics, so we'd want to keep a Vec or similar.
* Renaming `suffix` to `generational_suffix` is fine but we should either keep the old one around as an alias or bump the major version. I'm fine either way. If we change how anything gets parsed, in addition to just preserving information, that points to a major version bump.
* Is there a clean distinction between prefix and suffix honorifics? Off the top of my head I can't think of examples that aren't pretty clearly one or the other, but I don't know how smart we'd want to be about, e.g., trying to recognize something that's conventionally a prefix but shows up in suffix position and normalize it. I suspect anything like that is going to substantially expand the scope of what might already be a sizable diff.

**Comment by djudd** [comment]
@nokome I might have free time to work on this myself in the next few weeks, but there's an open question about distinguishing prefix & suffix honorifics which I'm not sure how to answer since I don't have a concrete use case and would just be doing this for fun. Do you have thoughts and/or a sample dataset that I could play with?

**Comment by nokome** [comment]
Thanks @djudd, I obviously didn't get to this myself, but am still keen to be able to use it.

The reason I suggested distinguishing prefix & suffix honorifics is that we do so in our schema for https://schema.stenci.la/Person which in turn follows https://schema.org/Person which distinguishes between the two.

The latter says:

- honorificPrefix: An honorific prefix preceding a Person's name such as Dr/Mrs/Mr.
- honorificSuffix: An honorific suffix following a Person's name such as M.D. /PhD/MSCSW.

So maybe the approach should be to compile a list of expected strings for each, swapping them if needs be, but also allowing for unexpected strings in either.

I don't have a suitable dataset of names right now but happen to be working on a tangential topic over the next week so could perhaps generate one.

**Comment by nokome** [comment]
Also, there is obviously a lot of prior art that can be made use of. See for example the very useful set of links at https://github.com/dschnelldavis/parse-full-name#credits-and-precursors, which includes "Title lists modified from". I've used `parse-full-name` in JavaScript code with success, maybe it's worth starting by porting it's approach to honorifics?

**Comment by djudd** [comment]
@nokome finally got to this and just merged a first pass at it - that last link was helpful and I've added it to the prior art in the README.

If you have a chance I'd love to know how well it works for you, or if you uncover any issues.

**Comment by nokome** [comment]
Thanks @djudd for taking the time to do this 🙏. I'll try it out and let you know how it goes.
